std = "lua54"
max_line_length = false

globals = {
    "ShinkiliDB",
    "BlizzShinDB",
    "ShinkiliLogic",
    "ShinkiliLocale",
    "ShinkiliSecret",
    "ShinkiliTrack",
    "ShinkiliEval",
    "ShinkiliSimcData",
    "SLASH_SHINKILI1",
    "SLASH_SHINKILI2",
    SlashCmdList = {
        fields = {
            SHINKILI = {},
        },
    },
}

files["Shinkili/ShinkiliSimcData.lua"] = {
    globals = {
        ShinkiliSimcData = {
            fields = {
                version = {},
                specs = {other_fields = true},
            },
        },
    },
}

read_globals = {
    "CreateFrame",
    "UIParent",
    -- 12.0 secret-value surface
    "issecretvalue",
    "C_Secrets",
    "C_UnitAuras",
    "InCombatLockdown",
    "UnitPower",
    "UnitPowerMax",
    "UnitPowerDisplayMod",
    "UnitHealth",
    "UnitHealthMax",
    "GetActionInfo",
    "GetSpellBaseCooldown",
    "C_ActionBar",
    "Minimap",
    "GameTooltip",
    "GetCursorPosition",
    "IsSpellOverlayed",
    "IsUsableSpell",
    "IsAltKeyDown",
    "IsControlKeyDown",
    "IsShiftKeyDown",
    "ClearOverrideBindings",
    "SetOverrideBindingClick",
    "UnitClass",
    "GetSpecialization",
    "UnitCanAttack",
    "UnitIsDead",
    "UnitExists",
    "GetTime",
    "GetSpellCooldown",
    "C_NamePlate",
    "C_SpellActivationOverlay",
    "C_AssistedCombat",
    "ShinkiliLocale",
    "ShinkiliSimcData",
    "C_Spell",
    "C_SpellBook",
    "C_Timer",
    "Enum",
    "FauxScrollFrame_GetOffset",
    "FauxScrollFrame_OnVerticalScroll",
    "FauxScrollFrame_Update",
    "GetNormalizedRealmName",
    "GetRealmName",
    "GetSpellCooldown",
    "unpack",
    "SlashCmdList",
    "UnitFullName",
    "UIDropDownMenu_AddButton",
    "UIDropDownMenu_CreateInfo",
    "UIDropDownMenu_Initialize",
    "UIDropDownMenu_JustifyText",
    "UIDropDownMenu_SetSelectedValue",
    "UIDropDownMenu_SetText",
    "UIDropDownMenu_SetWidth",
    "UnitCastingInfo",
    "UnitChannelInfo",
    "UnitEmpoweredStageDurations",
}
